config/routes.rb
Madmin::Application.routes.draw do

  match '/login/new' => 'logins#new', :as => :new_login
  match '/login/cookiesrequired' => 'logins#cookiesrequired', :as => :cookiesrequired_login
  match '/login' => 'logins#create', :as => :create_login
  match '/logout' => 'logins#destroy', :as => :destroy_login
  match '/myself' => 'users#myself', :as => :myself

  resources :domains do
    member do
      get 'confirm_destroy'
    end
    resources :forwards do
      member do
        get 'confirm_destroy'
      end
    end
    resources :users do
      member do
        get 'confirm_destroy'
      end
      resources :dyndns_hostnames do
        member do
          get 'confirm_destroy'
        end
      end
    end
  end

  root :to => 'logins#new'

end

app/controllers/logins_controller.rb
# -*- encoding : utf-8 -*-
class LoginsController < ApplicationController
  skip_before_filter :authenticate
  skip_load_and_authorize_resource
  skip_authorization_check

  def cookiesrequired
    if session[:cookietest] == true
      redirect_to new_login_url
    end
  end

  def new
    # No session-cookie means first request or cookies disabled. If it's the
    # first request the cookierequired-test will redirect back here and then
    # we've got a session.
    if cookies[sessionkey].blank?
      session[:cookietest] = true
      redirect_to cookiesrequired_login_url
      return
    end
  end

  # login
  def create
    name, domain = params[:email].to_s.split('@')
    domain = Domain.find_by_name(domain)
    user = User.where(:name => name, :domain_id => domain.try(:id)).first
    if user.try(:authenticate, params[:password])
      session[:current_user_id] = user.id
      update_session_expiry
      if session[:return_to].present?
        redirect_to session[:return_to]
        session[:return_to] = nil
      else
        redirect_to [domain, user]
      end
    else
      respond_to do |format|
        format.html {
          flash[:alert] = 'Wrong username or password, please try again.'
          render :new, :status => 401
        }
        format.json {
          head :unauthorized
        }
      end
    end
  end

  # login
  def destroy
    log_out "Logout successful. Have a nice day!"
  end

  private

  def sessionkey
    Rails.application.config.session_options[:key]
  end
end

app/helpers/logins_helper.rb
# -*- encoding : utf-8 -*-
module LoginsHelper
end

app/views/logins/cookiesrequired.html.haml
%h1 Cookies required

.cookies-required#msg Session-cookies are required for this application. Please enable them in your browser.

.cookies-required#link= link_to 'Back to login', new_login_url

app/views/logins/new.html.haml
.page-header
  %h1= t :log_in

.col-sm-12.col-md-5.col-lg-3
  = form_tag(create_login_path) do
    .form-group
      = label_tag :email, 'Email'
      = text_field_tag :email, '', class: 'form-control'
    .form-group
      = label_tag :password, t(:password), :class => 'control-label'
      = password_field_tag :password, '', class: 'form-control'
    = submit_tag 'Login', class: 'btn btn-info'