config/routes.rb
Madmin::Application.routes.draw do

  match '/login/new' => 'logins#new', :as => :new_login
  match '/login/cookiesrequired' => 'logins#cookiesrequired', :as => :cookiesrequired_login
  match '/login' => 'logins#create', :as => :create_login
  match '/logout' => 'logins#destroy', :as => :destroy_login
  match '/myself' => 'users#myself', :as => :myself

  resources :domains do
    member do
      get 'confirm_destroy'
    end
    resources :forwards do
      member do
        get 'confirm_destroy'
      end
    end
    resources :users do
      member do
        get 'confirm_destroy'
      end
      resources :dyndns_hostnames do
        member do
          get 'confirm_destroy'
        end
      end
    end
  end

  root :to => 'logins#new'

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  has_secure_password
  belongs_to :domain
  has_many :dyndns_hostnames, order: :name, dependent: :destroy
  attr_accessible :name, :password, :password_confirmation, :domain_id, :role, :forward_destination
  validates :name, 
            presence: { format: { with: EMAIL_LOCALPART_REGEXP } },
            uniqueness: { scope: :domain_id },
            exclusion: { in: lambda { |u| Domain.forwards_names(u.domain_id) },
                         message: 'is taken by forward.' }
  validates :domain, :presence => true
  validates :role, :inclusion => { :in => ROLES }
  # Only validate forward_destination if present.
  # TODO: allow multiple concatenated addresses.
  validates :forward_destination, :presence => true,
      :format => { :with => EMAIL_ADDR_REGEXP },
      :if => Proc.new { |user| user.forward_destination.present? }
  before_destroy :destroyable?

  default_scope order(:name)

  after_destroy :delete_user_data

  def self.find_all_by_initial(initial)
    where("name like '#{initial}%'")
  end

  def self.latest(limit=20)
    order(:created_at).limit(limit)
  end

  def self.superadmins
    where(role: 'superadmin')
  end

  def self.any_superadmins_left?(obj, field)
    if superadmins.where("#{field} != #{obj.id}").blank?
      obj.errors[:base] << 'Must not delete the last superadmin!'
      false
    else
      true
    end
  end

  def delete_user_data
    logger.info "Deleting user-data for #{self}:"
    logger.info `#{Rails.root}/bin/delete-mail-data.sh '#{domain.name}' '#{name}'`.chomp
  end

  def destroyable?
    # Postmaster-account may not be deleted other than with its domain.
    if self.postmaster?
      self.errors[:base] << 'Must not delete postmaster of domain!'
      ret = false
    else
      ret = true
    end
    ret && self.class.any_superadmins_left?(self, :id)
  end

  def has_role?(role)
    ROLES.index(role.to_s) <= ROLES.index(self.role.to_s).to_i
  end

  def admin?
    self.postmaster? || has_role?(:admin)
  end

  def postmaster?
    self.name == 'postmaster'
  end

  def superadmin?
    has_role?(:superadmin)
  end

  def to_s
    email
  end

  def self.find_by_email(email)
    name, domain_name = email.split('@')
    domain = Domain.find_by_name(domain_name)
    self.where(:name => name, :domain_id => domain.try(:id)).first || false
  end

  def as_json(options={})
    @json ||= {
      :name => self.name,
      :id => self.id,
      :domain => {
        :id => self.domain.id,
        :name => self.domain.name
        },
      :role => self.role,
      :forward_destination => self.forward_destination,
      dyndns_hostnames: self.dyndns_hostnames.map(&:name)
    }
  end

  def email
    [self.name, self.domain.name].join '@'
  end

  # TODO: authenticate against madmin_gauth if present in $PATH
  def authenticate(input)
    if password_digest.blank?
      logger.info "BCrypt-attribute is blank, attempting authentication against legacy password"
      if authenticate_oldpw(input)
        logger.info "Saving password into BCrypt-attribute."
        self.password = input
        self.save!
        self
      else
        false
      end
    else
      super(input)
    end
  end

  def authenticate_oldpw(input)
    # Crypt finds the salt itself from the hashed string.
    old_pwstring == input.crypt(old_pwstring)
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  load_resource :domain, except: :myself
  skip_load_and_authorize_resource only: :myself

  def myself
    authorize! :show, current_user
    respond_to do |format|
      format.html { redirect_to [current_user.domain, current_user] }
      format.json { render json: current_user }
    end
  end

  def index
    filtered_index
  end

  def confirm_destroy
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def new
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def edit
  end

  def create
    @user.domain_id = @domain.id
    @user.role = ROLES.first

    respond_to do |format|
      if @user.save
        format.html {
          redirect_to [@domain, @user], notice: 'User was successfully created.'
        }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @user.password_digest.blank? && params[:user][:password].blank?
      # Temporarily allow setting forward_destination and role for users
      # without a password_digest, until we can disable/change the
      # validations of has_secure_password (works only with rails 4.x)
      if (fw_dest = params[:user][:forward_destination]).present?
        if fw_dest.match(EMAIL_ADDR_REGEXP)
          @user.update_attribute(:forward_destination, fw_dest)
        else
          @user.errors.add(:forward_destination, 'is invalid')
        end
      end

      if (role = params[:user][:role]).present?
        if ROLES.include?(role)
          @user.update_attribute(:role, role)
        else
          @user.errors.add(:role, 'is invalid')
        end
      end
    else
      @user.update_attributes(params[:user])
    end

    respond_to do |format|
      if @user.errors.blank?
        format.html {
          redirect_to [@user.domain, @user],
              notice: 'User was successfully updated.'
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      domain = @user.domain
      if @user.destroy
        format.html { redirect_to [domain, 'users'] }
        format.json { head :no_content }
      else
        format.html { redirect_to [domain, @user], alert: @user.errors[:base] }
        format.json do
          render json: @user.errors[:base], status: :unprocessable_entity
        end
      end
    end
  end

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/_user.html.haml
%li.user= link_to user.name, domain_user_path(@domain, user)

app/views/users/confirm_destroy.html.haml
%h1 Are you sure you want to delete the user #{@user.email}?

= form_for([@domain, @user], :html => { :method => :delete }) do |f|
  = submit_tag t("destroy"), :class => 'btn btn-danger'
  = link_to :cancel, [@domain, @user]

app/views/users/edit.html.haml
.page-header
  %h1= t('edit_name', name: @user.email)

= form_for([@domain, @user]) do |f|
  = render :partial => 'shared/form_errors', :locals => { :obj => @user }

  .col-sm-12.col-md-9.col-lg-6
    .panel.panel-default
      .panel-heading= t(:change_password)
      .panel-body
        .form-group
          = f.password_field :password, class: 'form-control', placeholder: 'Password'
        .form-group
          = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password confirmation'
        = f.submit t(:save), class: 'btn btn-primary'

  .col-sm-12.col-md-9.col-lg-6
    .panel.panel-default
      .panel-heading= t :set_forward
      .panel-body
        .form-group
          = f.text_field :forward_destination, class: 'form-control', placeholder: t(:destination)
        = f.submit t(:save), class: 'btn btn-primary'

  - if (current_user.superadmin? && ! @user.postmaster?)
    .col-sm-12.col-md-9.col-lg-6
      .panel.panel-default
        .panel-heading= t(:assign_role)
        .panel-body
          -# TODO: let admins uplevel others to admin — but don't let them uplevel anyone to superadmin.
          -# TODO: use cancan's roles for rights-checking.
          .form-group
            = f.collection_select :role, ROLES, :to_s, :humanize, {}, class: 'form-control'
          = f.submit t(:save), class: 'btn btn-primary'


.col-sm-12
  = link_to t(:cancel), [@domain, @user], class: 'btn btn-default'

app/views/users/index.html.haml
.page-header
  %h1
    - if @filter_initial.present?
      #{@filter_initial}&hellip;
    - else
      #{t(:latest_users)}
    @#{@domain}
  = render 'shared/initials_filter'

.pull-right= link_to t('.users.new'), new_domain_user_path(@domain), :class => 'btn btn-primary'

%ul= render @users

app/views/users/new.html.haml
.col-sm-12.col-md-9.col-lg-6
  .panel.panel-primary
    .panel-heading= t 'new_user'
    .panel-body
      = form_for([@domain, @user], html: { class: 'form', role: :form}) do |f|
        = render :partial => 'shared/form_errors', :locals => { :obj => @user }

        .form-group
          = f.label :name
          .input-group
            = f.text_field :name, class: 'form-control'
            %span.input-group-addon @#{@domain.name}

        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: 'form-control'

        .form-group
          = f.label :forward_destination
          = f.text_field :forward_destination, class: 'form-control'

        - if (current_user.superadmin? && ! @user.postmaster?)
          .form-group
            -# TODO: let admins uplevel others to admin — but don't let them uplevel anyone to superadmin.
            -# TODO: use cancan's roles for rights-checking.
            = f.label :role
            = f.collection_select :role, ROLES, :to_s, :humanize, {}, class: 'form-control'

        .form-group
          = f.submit t(:save), class: 'btn btn-primary'
          = link_to t(:cancel), [@domain, @user], class: 'btn btn-link'

app/views/users/show.html.haml
.page-header
  %h1= @user.email

.col-sm-12.col-md-8.col-lg-6
  .panel.panel-default
    .panel-heading
      = t(:account)
      %ul.pull-right.list-inline
        %li= link_to t(:edit), edit_domain_user_path(@domain, @user) 
        - if @user.destroyable?
          %li= link_to t('destroy'), confirm_destroy_domain_user_path(@domain, @user), class: 'text-danger'

    .panel-body
      %dl.dl-horizontal

        %dt= t :password
        %dd
          - if @user.password_digest.present?
            .text-success good
          - else
            .text-warning old

        %dt= t :forward
        %dd
          - if @user.forward_destination.present?
            = @user.forward_destination
            %small.text-warning (Email is <strong>not stored</strong>.)
          - else
            .text-info Email is not forwarded.

        %dt= t(:role)
        %dd
          - if @user.postmaster?
            = @user.superadmin? ? 'Superadmin' : 'Admin'
          - else
            = (@user.role.presence || User::ROLES.first).humanize

        %br
        %small.text-muted
          %dt= User.human_attribute_name(:created_at)
          %dd= l @user.created_at
          %dt= User.human_attribute_name(:updated_at)
          %dd= l @user.updated_at


.col-sm-12.col-md-6.col-lg-6
  .panel.panel-default#dyndns_hostnames
    .panel-heading Dyndns Hostnames
    .panel-body
      .pull-right= link_to t('new'), new_domain_user_dyndns_hostname_path(@domain, @user), :class => 'btn btn-primary'

      %ul
        - @user.dyndns_hostnames.each do |hostname|
          %li
            = hostname.name
            = link_to t('.edit'), edit_domain_user_dyndns_hostname_path(@domain, @user, hostname), :class => 'btn btn-small'
            = link_to t('.destroy'), confirm_destroy_domain_user_dyndns_hostname_path(@domain, @user, hostname), :class => 'btn btn-small btn-danger'
      .clearfix