config/routes.rb
Madmin::Application.routes.draw do

  match '/login/new' => 'logins#new', :as => :new_login
  match '/login/cookiesrequired' => 'logins#cookiesrequired', :as => :cookiesrequired_login
  match '/login' => 'logins#create', :as => :create_login
  match '/logout' => 'logins#destroy', :as => :destroy_login
  match '/myself' => 'users#myself', :as => :myself

  resources :domains do
    member do
      get 'confirm_destroy'
    end
    resources :forwards do
      member do
        get 'confirm_destroy'
      end
    end
    resources :users do
      member do
        get 'confirm_destroy'
      end
      resources :dyndns_hostnames do
        member do
          get 'confirm_destroy'
        end
      end
    end
  end

  root :to => 'logins#new'

end

app/models/domain.rb
# -*- encoding : utf-8 -*-
class Domain < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true
  has_many :users,  :order => :name, :dependent => :destroy
  has_many :forwards, :order => :name, :dependent => :destroy
  before_destroy :destroyable?
  after_destroy :delete_domain_data

  default_scope order(:name)

  def self.users_names(domain_id)
    resource_names(User, domain_id)
  end

  def self.forwards_names(domain_id)
    resource_names(Forward, domain_id)
  end

  def admins
    users.where(role: 'admin')
  end

  def delete_domain_data
    logger.info "Deleting domain-data for #{self}:"
    logger.info `#{Rails.root}/bin/delete-mail-data.sh '#{self}'`.chomp
  end

  def destroyable?
    User.any_superadmins_left?(self, :domain_id)
  end

  def as_json(options={})
    @json ||= {
      :name => self.name,
      :id => self.id,
      :users => self.users,
      :forwards => self.forwards
    }
  end
  
  def to_s
    name
  end

  private

  def self.resource_names(klass, domain_id)
    klass.select(:name).where(domain_id: domain_id).map(&:name)
  end
end

app/controllers/domains_controller.rb
# -*- encoding : utf-8 -*-
class DomainsController < ApplicationController

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domains }
    end
  end

  def confirm_destroy
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @domain }
    end
  end

  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domain }
    end
  end

  def filter_params
    if request['action'] == 'create'
      @user_params = params['domain'].delete('user')
    end
  end

  def create
    if @domain.save
      @user = User.new(@user_params)
      @user.name = 'postmaster'
      @user.role = 'admin'
      @user.domain_id = @domain.id

      if ! @user.save
        @domain.delete
      end
    end

    respond_to do |format|
      if @domain.errors.blank? && @user.errors.blank?
        format.html {
          redirect_to @domain,
              notice: "Domain #{@domain.name} was successfully created."
        }
        format.json { render json: @domain, status: :created, location: @domain }
      else
        format.html { render action: "new" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @domain.destroy
        format.html {
          redirect_to domains_url,
              notice: "Domain #{@domain.name} was successfully deleted."
        }
        format.json { head :no_content }
      else
        format.html { redirect_to @domain, alert: @domain.errors[:base] }
        format.json { render json: @domain.errors[:base], status: :conflict }
      end
    end
  end

end

app/helpers/domains_helper.rb
# -*- encoding : utf-8 -*-
module DomainsHelper
end

app/views/domains/_domain.html.haml
%li= link_to domain.name, domain

app/views/domains/_form.html.haml
= form_for @domain, html: { class: 'form-horizontal' } do |f|
  = render partial: 'shared/form_errors', locals: { obj: @domain } if @domain.present?
  = render partial: 'shared/form_errors', locals: { obj: @user } if @user.present?
  .control-group
    = f.label :name, class: 'control-label' do
      Domain name
    .controls
      = f.text_field :name, class: 'text_field'
  .control-group
    = f.fields_for :user do |ff|
      .control-group
        = ff.label :password, class: 'control-label' do
          Postmaster password
        .controls
          = ff.password_field :password, class: 'text_field'
      .control-group
        = ff.label :password_confirmation, class: 'control-label'
        .controls
          = ff.password_field :password_confirmation, class: 'text_field'
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), domains_path, class: 'btn'

app/views/domains/confirm_destroy.html.haml
%h1 Are you sure you want to delete the domain #{@domain.name}?

= form_for(@domain, :html => { :method => :delete }) do |f|
  = submit_tag t('destroy'), :class => 'btn btn-danger'
  = link_to :cancel, @domain

app/views/domains/index.html.haml
.page-header
  %h1 Domains

.pull-right= link_to t('.new', :default => t("helpers.links.new")), new_domain_path, :class => 'btn btn-primary'

%ul= render @domains

app/views/domains/new.html.haml
.page-header
  %h1 #{t '.new'} domain
= render "form"

app/views/domains/show.html.haml
.page-header
  %h1= @domain.name

.well
  %h4 Meta
  .pull-right
    - if @domain.destroyable?
      = link_to t('.destroy', :default => t("helpers.links.destroy")), confirm_destroy_domain_path(@domain), :class => 'btn btn-danger'
  %ul
    %li #{t(:created_at)}: #{l @domain.created_at}.
    %li #{t(:updated_at)}: #{l @domain.updated_at}.

.well
  %h4 Admins
  %ul= render @domain.admins

.well
  %h4 Latest Users
  .pull-right= link_to t('.users.new', :default => t("helpers.links.new")), new_domain_user_path(@domain), :class => 'btn btn-primary'

  - if (users = @domain.users.latest(5)).present?
    %ul= render users
    = link_to t('more_users'), domain_users_path(@domain)
  .clearfix


.well
  %h4= t('latest_forwards')
  .pull-right= link_to t('.forwards.new', :default => t("helpers.links.new")), new_domain_forward_path(@domain), :class => 'btn btn-primary'

  - if (forwards = @domain.forwards.latest(5)).present?
    %ul= render forwards
    = link_to t('more_forwards'), domain_forwards_path(@domain)
  .clearfix