config/routes.rb
Madmin::Application.routes.draw do

  match '/login/new' => 'logins#new', :as => :new_login
  match '/login/cookiesrequired' => 'logins#cookiesrequired', :as => :cookiesrequired_login
  match '/login' => 'logins#create', :as => :create_login
  match '/logout' => 'logins#destroy', :as => :destroy_login
  match '/myself' => 'users#myself', :as => :myself

  resources :domains do
    member do
      get 'confirm_destroy'
    end
    resources :forwards do
      member do
        get 'confirm_destroy'
      end
    end
    resources :users do
      member do
        get 'confirm_destroy'
      end
      resources :dyndns_hostnames do
        member do
          get 'confirm_destroy'
        end
      end
    end
  end

  root :to => 'logins#new'

end

app/models/forward.rb
# -*- encoding : utf-8 -*-
class Forward < ActiveRecord::Base
  belongs_to :domain
  attr_accessible :destination, :name, :domain_id
  validates :name,
            presence: { format: { with: EMAIL_LOCALPART_REGEXP } },
            uniqueness: { scope: :domain_id },
            exclusion: { in: lambda { |fw| Domain.users_names(fw.domain_id) },
                         message: 'is taken by user.' }
  validates :domain, presence: { message: 'does not exist' }
  validates :destination, presence: { format: { with: EMAIL_ADDR_REGEXP } }

  default_scope order(:name)

  # TODO: refactor with User
  def self.find_all_by_initial(initial)
    where("name like '#{initial}%'")
  end

  def self.latest(limit=20)
    order(:created_at).limit(limit)
  end

  def as_json(options={})
    @json ||= {
      :name => self.name,
      :id => self.id,
      :destination => self.destination
    }
  end

  def email
    [self.name, self.domain.name].join '@'
  end
end

app/controllers/forwards_controller.rb
# -*- encoding : utf-8 -*-
class ForwardsController < ApplicationController
  load_resource :domain

  def index
    filtered_index
  end


  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forward }
    end
  end

  def confirm_destroy
  end

  def show
  end

  def edit
  end

  def create
		@forward.domain_id=@domain.id

    respond_to do |format|
      if @forward.save
        format.html {
          redirect_to [@domain, @forward],
              notice: 'Forward was successfully created.'
        }
        format.json {
          render json: [@domain, @forward],
              status: :created, location: @forward
        }
      else
        format.html { render action: "new" }
        format.json {
          render json: @forward.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def update
    params.delete(:name)
    params.delete(:domain)

    respond_to do |format|
      if @forward.update_attributes(params[:forward])
        format.html {
          redirect_to [@domain, @forward],
              notice: 'Forward was successfully updated.'
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json {
          render json: @forward.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def destroy
    f = @forward.dup
    @forward.destroy

    respond_to do |format|
      format.html {
        redirect_to f.domain, notice: 'Forward was deleted.'
      }
      format.json { head :no_content }
    end
  end

end

app/helpers/forwards_helper.rb
# -*- encoding : utf-8 -*-
module ForwardsHelper
end

app/views/forwards/_form.html.haml
= form_for([@domain, @forward], :html => { :class => 'form-horizontal' }) do |f|
  = render :partial => 'shared/form_errors', :locals => { :obj => @forward }
  - if @forward.created_at.blank?
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        .input-append
          #{f.text_field :name}
          %span.add-on @#{@domain.name}
  .control-group
    = f.label :destination, :class => 'control-label'
    .controls= f.text_field :destination
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t(:cancel), [@domain, @forward], class: 'btn'

app/views/forwards/_forward.html.haml
%li.forward
  = link_to "#{forward.name} → #{forward.destination}", domain_forward_path(forward.domain, forward)

app/views/forwards/confirm_destroy.html.haml
%h1 Are you sure you want to delete the forward #{@forward.email} &rarr; #{@forward.destination}?

= form_for([@domain, @forward], :html => { :method => :delete }) do |f|
  = submit_tag t('destroy'), :class => 'btn btn-danger'
  = link_to :cancel, [@domain, @forward]

app/views/forwards/edit.html.haml
.page-header
  %h1 Editing forward #{@forward.name}@#{@domain.name}

= render 'form'

= link_to t(:cancel), [@domain, @forward]

app/views/forwards/index.html.haml
.page-header
  %h1
    - if @filter_initial.present?
      #{@filter_initial}&hellip;
    - else
      #{t(:latest_forwards)}
    @#{@domain}
  = render 'shared/initials_filter'

.pull-right= link_to t('.new'), new_domain_forward_path(@domain), :class => 'btn btn-primary'


%ul= render @forwards

app/views/forwards/new.html.haml
.page-header
  %h1 New forward

= render 'form'

app/views/forwards/show.html.haml
.page-header
  %h1 #{@forward.email} &rarr; #{@forward.destination}

= render :partial => 'shared/form_errors', :locals => { :obj => @forward }

.well
  %h4 Meta
  .pull-right
    = link_to 'Edit', edit_domain_forward_path(@domain, @forward), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), confirm_destroy_domain_forward_path(@domain, @forward), :method => "delete", :class => 'btn btn-danger'
  %ul
    %li #{Forward.human_attribute_name(:created_at)}: #{l @forward.created_at}.
    %li #{Forward.human_attribute_name(:updated_at)}: #{l @forward.updated_at}.

  .clearfix